FROM node:22-alpine AS development

WORKDIR /app

RUN apk add --no-cache curl python3 make g++
RUN corepack enable && corepack prepare pnpm@10.17.1 --activate

COPY package.json pnpm-lock.yaml* .npmrc ./
COPY prisma ./prisma/

RUN pnpm install --frozen-lockfile
RUN pnpm exec prisma generate

EXPOSE 3333

CMD ["pnpm", "exec", "tsx", "watch", "src/server.ts"]
