FROM node:22-alpine AS development

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

EXPOSE 3333

CMD ["npx", "tsx", "watch", "src/server.ts"]
